# Generated by Django 3.2.6 on 2022-04-15 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Privacy name', max_length=255)),
                ('code', models.CharField(help_text='Privacy code', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_privacy_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_privacy_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_privacy_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'privacy',
                'verbose_name_plural': 'privacy',
                'db_table': 'privacy',
            },
        ),
        migrations.CreateModel(
            name='Formality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Formality name', max_length=255)),
                ('code', models.CharField(help_text='Formality code', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_formality_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_formality_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_formality_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'formality',
                'verbose_name_plural': 'formality',
                'db_table': 'formality',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Privacy name', max_length=255)),
                ('code', models.CharField(help_text='Privacy code', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_eventtype_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_eventtype_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_eventtype_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'event_type',
                'verbose_name_plural': 'event_type',
                'db_table': 'event_type',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Event name', max_length=255)),
                ('cover', models.CharField(help_text='Cover name', max_length=255)),
                ('venue', models.CharField(blank=True, help_text='Tên địa điểm tổ chức sự kiện', max_length=300, null=True)),
                ('tagline', models.CharField(blank=True, help_text='Tag giúp tìm kiếm event trong hinnox', max_length=100, null=True)),
                ('from_date', models.DateTimeField(blank=True, help_text='Ngày bắt đầu', null=True)),
                ('to_date', models.DateTimeField(blank=True, help_text='Ngày kết thúc', null=True)),
                ('description', models.TextField(blank=True, help_text='Description', null=True)),
                ('co_host', models.ManyToManyField(blank=True, related_name='event_event_co_hosts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_event_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_event_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventtype')),
                ('formality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.formality')),
                ('owner', models.ForeignKey(blank=True, help_text='Người đứng ra tổ chức sự kiện', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_event_owner', to=settings.AUTH_USER_MODEL)),
                ('privacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.privacy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_event_updated_by', to=settings.AUTH_USER_MODEL)),
                ('users_interested_in', models.ManyToManyField(blank=True, help_text='User quan tâm tới sự kiện', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'event',
            },
        ),
    ]
