# Generated by Django 3.2.6 on 2022-04-15 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='schedule',
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ManyToManyField(blank=True, help_text='Người đứng ra tổ chức sự kiện', related_name='event_event_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
