# Generated by Django 3.2.6 on 2022-04-21 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(blank=True, help_text='Uid', max_length=255, null=True)),
                ('stage', models.CharField(choices=[('INVITED', 'INVITED'), ('JOINED', 'JOINED')], default='JOINED', max_length=10)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_eventparticipant_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_eventparticipant_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, help_text='Event', null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('inviter_id', models.ForeignKey(blank=True, help_text='Người mời tham gia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_eventparticipant_inviter', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_eventparticipant_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event participant',
                'verbose_name_plural': 'Event participants',
                'db_table': 'event_participant',
            },
        ),
    ]
