# Generated by Django 3.2.6 on 2022-04-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, help_text='Event name', max_length=255, null=True),
        ),
    ]
