# Generated by Django 3.2.6 on 2022-04-21 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0002_eventparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='uid',
            field=models.ForeignKey(blank=True, help_text='Người tham gia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_eventparticipant_uid', to=settings.AUTH_USER_MODEL),
        ),
    ]
