# Generated by Django 3.2.6 on 2022-04-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=models.CharField(blank=True, help_text='Cover name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Event name', max_length=255),
        ),
    ]
