# Generated by Django 3.2.6 on 2022-05-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_eventparticipant_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.TextField(blank=True, help_text='Mô tả ngắn về sự kiện', null=True),
        ),
    ]
