# Generated by Django 3.2.6 on 2022-04-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20220416_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formality',
            name='id',
        ),
        migrations.AlterField(
            model_name='formality',
            name='code',
            field=models.CharField(help_text='Formality code', max_length=255, primary_key=True, serialize=False),
        ),
    ]
