# Generated by Django 3.2.6 on 2022-06-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='business_level_code',
            field=models.CharField(blank=True, help_text='Business Level Code', max_length=300, null=True),
        ),
    ]
