# Generated by Django 3.2.6 on 2022-08-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_business_level_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='co_host',
        ),
        migrations.AddField(
            model_name='event',
            name='co_host',
            field=models.TextField(blank=True, help_text='Co host', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.CharField(blank=True, help_text='Người đứng ra tổ chức sự kiện', max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='event',
            name='users_interested_in',
        ),
        migrations.AddField(
            model_name='event',
            name='users_interested_in',
            field=models.TextField(blank=True, help_text='User interested in', null=True),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='inviter_id',
            field=models.CharField(blank=True, help_text='Người mời tham gia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='uid',
            field=models.CharField(blank=True, help_text='Người được mời', max_length=100, null=True),
        ),
    ]
