# Generated by Django 3.2.6 on 2022-08-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20220803_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link_online',
            field=models.CharField(blank=True, help_text='Link online', max_length=300, null=True),
        ),
    ]
