# Generated by Django 3.2.6 on 2022-10-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_link_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='disabled_by',
            field=models.CharField(blank=True, help_text='Người disable sự kiện', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_disable',
            field=models.BooleanField(default=False),
        ),
    ]
