# Generated by Django 3.1.2 on 2022-03-17 03:43

import cloudinary.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import event.models.contest
import event.models.support.generate


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=255, verbose_name='Category name')),
                ('thumb', cloudinary.models.CloudinaryField(blank=True, help_text='Thumbnail of category', max_length=255, null=True, verbose_name='thumb')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'hinnox_categories',
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(help_text='Tiêu đề của cuộc thi', max_length=300)),
                ('street_address', models.CharField(blank=True, help_text='Địa chỉ chi tiết của cuộc thi', max_length=300, null=True)),
                ('picture', cloudinary.models.CloudinaryField(blank=True, help_text='File ảnh', max_length=255, null=True, verbose_name='image')),
                ('picture_url', models.URLField(blank=True, help_text='URL ảnh đại diện của cuộc thi', max_length=300, null=True)),
                ('tagline', models.CharField(blank=True, help_text='Tag giúp tìm kiếm cuộc thi trong hinnox', max_length=100, null=True)),
                ('description', models.CharField(blank=True, help_text='Mô tả về cuộc thi', max_length=2500, null=True)),
                ('date_created', models.DateTimeField(default=event.models.contest.today, help_text='Ngày tạo cuộc thi')),
                ('url', models.CharField(blank=True, help_text='Địa chỉ tùy chỉnh đến trang của cuộc thi https://hinnox.com/contest-url', max_length=300, null=True)),
                ('from_date', models.DateTimeField(blank=True, help_text='Ngày bắt đầu', null=True)),
                ('to_date', models.DateTimeField(blank=True, help_text='Ngày kết thúc', null=True)),
                ('last_modified', models.DateTimeField(blank=True, help_text='Thời gian sửa đổi lần cuối', null=True)),
                ('city', models.ForeignKey(blank=True, help_text='Thành phố tổ chức cuộc thi', null=True, on_delete=django.db.models.deletion.CASCADE, to='event.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hinnox_contests',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tiêu đề của deal', max_length=512)),
                ('slug', models.SlugField(max_length=512)),
                ('company_url', models.URLField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=3, help_text='Giá trị deal', max_digits=40)),
                ('money_saved', models.DecimalField(decimal_places=3, help_text='Giá trị tiết kiệm được nếu sử dụng deal', max_digits=40)),
                ('is_beta_phase', models.BooleanField(default=False, help_text='Chỉ ra sản phẩm đang trong giai đoạn beta')),
                ('briefly_describe', models.CharField(blank=True, help_text='Mô tả ngắn gọn về deal 2500 từ', max_length=2500, null=True)),
                ('detail', models.TextField(blank=True, help_text='Chi tiết về deal', null=True)),
                ('everyone', models.BooleanField(default=True, help_text='Cho phép deal được quảng cáo trực tiếp đến với các người dùng')),
                ('introduce_video_url', models.URLField(blank=True, help_text='Link video giới thiệu về deal', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Ngày tạo')),
                ('promote_code', models.CharField(blank=True, help_text='Code giảm giá cho deal', max_length=254, null=True)),
                ('limit', models.PositiveIntegerField(blank=-1, help_text='Giới hạn số lượng khách hàng sử dụng deal', null=True)),
                ('email_for_deal_redemption', models.EmailField(help_text='Email phản hồi hoàn trả deal từ khách hàng', max_length=254)),
                ('last_modified', models.DateTimeField(blank=True, help_text='Thời gian sửa đổi lần cuối', null=True)),
            ],
            options={
                'db_table': 'hinnox_deals',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=event.models.support.generate.gen_unique_number, max_length=30, unique=True)),
                ('name', models.CharField(help_text='Tên của tổ chức', max_length=1000)),
                ('picture', cloudinary.models.CloudinaryField(blank=True, help_text='File ảnh', max_length=255, null=True, verbose_name='image')),
                ('picture_url', models.URLField(blank=True, help_text='URL ảnh đại diện của tổ chức', null=True)),
                ('street_address', models.CharField(blank=True, help_text='Địa chỉ chi tiết của tổ chức', max_length=255, null=True)),
                ('url', models.CharField(blank=True, db_index=True, help_text='Địa chỉ tùy chỉnh đến trang của tổ chức https://hinnox.com/organization-url', max_length=300, null=True)),
                ('tagline', models.CharField(blank=True, help_text='Tag giúp tìm kiếm tổ chức trong hinnox', max_length=100, null=True)),
                ('description', models.CharField(blank=True, help_text='Mô tả tổng quan về tổ chức', max_length=2500, null=True)),
                ('last_modified', models.DateTimeField(blank=True, help_text='Thời gian sửa đổi lần cuối', null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.city')),
            ],
            options={
                'db_table': 'hinnox_organizations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Loại hình tổ chức ví dụ Fund, Institute, Accelerator', max_length=100)),
                ('code', models.CharField(blank=True, help_text='Code của loại hình tổ chức', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'loại hình tổ chức',
                'verbose_name_plural': 'OrganizationType - Loại hình tổ chức',
                'db_table': 'hinnox_organization_types',
            },
        ),
        migrations.CreateModel(
            name='PrivacySetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên cài đặt bảo mật public, insider(team, investor, advisor), investor only, team only', max_length=255, verbose_name='Tên cài đặt')),
                ('code', models.CharField(help_text='Mã <= 20 ký tự đại diện quyền riêng tư', max_length=20, unique=True, verbose_name='Mã quyền riêng tư')),
            ],
            options={
                'verbose_name': 'cài đặt riêng tư',
                'verbose_name_plural': 'PrivacySetting - Cài đặt riêng tư',
                'db_table': 'hinnox_privacy_settings',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(help_text='Giai đoạn của startup', max_length=125, verbose_name='Giai đoạn')),
            ],
            options={
                'verbose_name': 'giai đoạn',
                'verbose_name_plural': 'Stage - Giai đoạn của team/startup',
                'db_table': 'hinnox_stages',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='backend-dev, front-end dev etc.', max_length=255, null=True, verbose_name='Name')),
                ('thumb', cloudinary.models.CloudinaryField(blank=True, help_text='Thumbnail of type', max_length=255, null=True, verbose_name='thumb')),
                ('category', models.ForeignKey(blank=True, help_text='Category', null=True, on_delete=django.db.models.deletion.CASCADE, to='event.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
                'db_table': 'hinnox_types',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=event.models.support.generate.gen_unique_number, max_length=30, unique=True)),
                ('name', models.CharField(help_text='Tên của nhóm', max_length=255)),
                ('picture', cloudinary.models.CloudinaryField(blank=True, help_text='File ảnh', max_length=255, null=True, verbose_name='image')),
                ('picture_url', models.URLField(blank=True, help_text='URL của ảnh đại diện của nhóm', max_length=300, null=True)),
                ('url', models.CharField(blank=True, db_index=True, help_text='Địa chỉ tùy chỉnh đến trang của nhóm https://hinnox.com/team-url', max_length=300, null=True)),
                ('founded_date', models.DateTimeField(blank=True, help_text='Ngày thành lập nhóm', null=True)),
                ('tagline', models.CharField(blank=True, help_text='Tag giúp tìm kiếm team trong hinnox', max_length=100, null=True)),
                ('android_app_link', models.URLField(blank=True, help_text='URL sản phẩm ứng dụng android', max_length=300, null=True)),
                ('ios_app_link', models.URLField(blank=True, help_text='URL sản phẩm ứng dụng ios', max_length=300, null=True)),
                ('description', models.CharField(blank=True, help_text='Mô tả tổng quan về nhóm', max_length=2500, null=True)),
                ('is_startup', models.BooleanField(default=False)),
                ('vision', models.TextField(blank=True, help_text='Tầm nhìn', null=True)),
                ('mission', models.TextField(blank=True, help_text='Sứ mệnh', null=True)),
                ('core_value', models.TextField(blank=True, help_text='Giá trị cốt lỗi', null=True)),
                ('phone_num', models.CharField(blank=True, help_text='Số điện thoại', max_length=12, null=True, unique=True)),
                ('street_address', models.CharField(blank=True, help_text='Địa chỉ chi tiết của team', max_length=512, null=True)),
                ('last_modified', models.DateTimeField(blank=True, help_text='Thời gian sửa đổi lần cuối', null=True)),
                ('use_for_studying', models.BooleanField(blank=True, default=False, help_text='User for studying', null=True)),
                ('stage', models.ForeignKey(help_text='Giai đoạn phát triển của một team', null=True, on_delete=django.db.models.deletion.CASCADE, to='event.stage')),
                ('user', models.ForeignKey(help_text='Admin của trang', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hinnox_teams',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Nội dung của bài viết')),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.contest')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='event.deal')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='event.organization')),
                ('privacy_setting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.privacysetting')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='event.team')),
                ('user', models.ForeignKey(help_text='User đăng bài', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hinnox_posts',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='event.organizationtype'),
        ),
        migrations.AddField(
            model_name='organization',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.team'),
        ),
        migrations.AddField(
            model_name='deal',
            name='types',
            field=models.ManyToManyField(db_table='hinnox_deal_type', help_text='Lĩnh vực của deal đang thực hiện', to='event.Type'),
        ),
        migrations.AddField(
            model_name='contest',
            name='organization',
            field=models.ForeignKey(help_text='Tổ chức tạo cuộc thi', on_delete=django.db.models.deletion.CASCADE, to='event.organization'),
        ),
        migrations.AddField(
            model_name='contest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contest',
            name='users_interested_in',
            field=models.ManyToManyField(blank=True, help_text='User quan tâm tới cuộc thi', to=settings.AUTH_USER_MODEL),
        ),
    ]
