# generate data
# from models import Type
#
# data = [{"category_name":"Design","category_sub":[{"name":"3D & Animation"},{"name":"Graphic Design & Illustration"},{"name":"Design Tools"},{"name":"Web Design"},{"name":"Other in Design"},{"name":"Architectural Design"},{"name":"Game Design"},{"name":"User Experience Design"},{"name":"Fashion Design"},{"name":"Interior Design"}]},{"category_name":"Design","category_sub":[{"name":"Digital Marketing"},{"name":"Social Media Marketing"},{"name":"Content Marketing"},{"name":"Search Engine Optimization"},{"name":"Marketing Fundamentals"},{"name":"Video & Mobile Marketing"},{"name":"Affiliate Marketing"},{"name":"Advertising"},{"name":"Branding"},{"name":"Other in Marketing"}]},{"category_name":"Lifestyle","category_sub":[{"name":"Arts & Crafts"},{"name":"Esoteric Practices"},{"name":"Food & Beverage"},{"name":"Other in Lifestyle"},{"name":"Beauty & Makeup"},{"name":"Gaming"},{"name":"Travel"},{"name":"Pet Care & Training"},{"name":"Home Improvement"},{"name":"Nutrition"}]},{"category_name":"Photography & Video","category_sub":[{"name":"Video Design"},{"name":"Digital Photography"},{"name":"Photography Tools"},{"name":"Photography"},{"name":"Other in Photography & Video"},{"name":"Portrait Photography"},{"name":"Commercial Photography"},{"name":"Mobile Development"},{"name":"Teacher Training"}]},{"category_name":"Health & Fitness","category_sub":[{"name":"General Health"},{"name":"Fitness"},{"name":"Mental Health"},{"name":"Yoga"},{"name":"Nutrition"},{"name":"Sports"},{"name":"Other in Health & Fitness"},{"name":"Dance"},{"name":"Meditation"},{"name":"Self Defense"}]},{"category_name":"Music","category_sub":[{"name":"Instruments"},{"name":"Music Production"},{"name":"Music Fundamentals"},{"name":"Music Software"},{"name":"Music Techniques"},{"name":"Vocal"},{"name":"Other in Music"}]},{"category_name":"Teaching & Academics","category_sub":[{"name":"Language"},{"name":"Engineering"},{"name":"Math"},{"name":"Test Prep"},{"name":"Online Education"},{"name":"Teacher Training"},{"name":"Other in Teaching & Academics"},{"name":"Science"},{"name":"Humanities"},{"name":"Social Science"}]}]
#
# data_up = []
# for d in data:
#     sub_name = d['category_name']
#     for sub in d['category_sub']:
#         data_up.append(Type(category_name=sub_name, type_name=sub['name']))
# Type.objects.bulk_create(data_up)