# Generated by Django 3.2.6 on 2022-04-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refaccount',
            options={'verbose_name': 'eventcenter Reference Account', 'verbose_name_plural': 'eventcenter Center Reference Accounts'},
        ),
    ]
