# Generated by Django 3.2.6 on 2022-04-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccount',
            name='id',
            field=models.TextField(default='263ece6763944402a69966d61863fcc0', primary_key=True, serialize=False),
        ),
    ]
