# Generated by Django 3.2.6 on 2022-04-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccount',
            name='id',
            field=models.UUIDField(default='b9f44426c9a2496896427c5606bf4273', primary_key=True, serialize=False),
        ),
    ]
