# Generated by Django 3.2.6 on 2022-04-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_refaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccount',
            name='id',
            field=models.TextField(default='e3f5090cdc3442c195094e694933cfe5', primary_key=True, serialize=False),
        ),
    ]
