# Generated by Django 3.2.6 on 2022-04-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_refaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccount',
            name='id',
            field=models.TextField(default='465ac6bb92ab4f04835f3e322b7a4486', primary_key=True, serialize=False),
        ),
    ]
