# Generated by Django 3.2.6 on 2022-04-15 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_refaccount_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refaccount',
            options={'verbose_name': 'event Reference Account', 'verbose_name_plural': 'event  Reference Accounts'},
        ),
        migrations.AlterModelTable(
            name='refaccount',
            table='event_ref_account',
        ),
    ]
