# Generated by Django 3.2.6 on 2022-04-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_refaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccount',
            name='id',
            field=models.TextField(default='532f434fa81e4cb7a07429ddf6dfeec2', primary_key=True, serialize=False),
        ),
    ]
