# Generated by Django 3.2.6 on 2022-04-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_refaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccount',
            name='id',
            field=models.TextField(default='7c8f2f238dfd43949a734f01018b0590', primary_key=True, serialize=False),
        ),
    ]
