# Generated by Django 3.2.6 on 2022-04-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_refaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccount',
            name='id',
            field=models.TextField(default='f4f5bc08ab55460c90e854afff54464f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='refaccount',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
