# Generated by Django 3.2.6 on 2022-04-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_refaccount_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='refaccount',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='refaccount',
            name='id',
            field=models.TextField(default='bfbff41c639146fba9eb5724e6711873', primary_key=True, serialize=False),
        ),
    ]
