# Generated by Django 3.2.6 on 2022-04-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220418_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccount',
            name='id',
            field=models.TextField(default='6b4ca486a4f845d49cf3af02ee51af73', primary_key=True, serialize=False),
        ),
    ]
