# Generated by Django 3.2.6 on 2022-04-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_refaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccount',
            name='id',
            field=models.TextField(default='de4c5d986d2944df8f56d7cb4a64c631', primary_key=True, serialize=False),
        ),
    ]
