# Generated by Django 3.2.6 on 2022-04-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_refaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccount',
            name='id',
            field=models.TextField(default='7504bf59ff3046c28dd15277ff7ab377', primary_key=True, serialize=False),
        ),
    ]
