# Generated by Django 3.2.6 on 2022-04-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_refaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccount',
            name='id',
            field=models.TextField(default='dc8568c1a6df47c29f84063f781710ef', primary_key=True, serialize=False),
        ),
    ]
