# Generated by Django 3.2.6 on 2022-04-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_refaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccount',
            name='id',
            field=models.TextField(default='2026300a3f7745b9bff1b4f570ab39b5', primary_key=True, serialize=False),
        ),
    ]
