# Generated by Django 3.2.6 on 2022-04-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_refaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccount',
            name='id',
            field=models.TextField(default='81b3823ed85845e99b752b079e6d9ff9', primary_key=True, serialize=False),
        ),
    ]
