# Generated by Django 3.2.6 on 2022-04-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_refaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccount',
            name='id',
            field=models.TextField(default='5190d34e53f442289105082ac3bd20bd', primary_key=True, serialize=False),
        ),
    ]
