# Generated by Django 3.2.6 on 2022-06-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_refaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccount',
            name='id',
            field=models.TextField(default='9ee72f6420e549c19580434397f51bea', primary_key=True, serialize=False),
        ),
    ]
