# Generated by Django 3.2.6 on 2022-08-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_refaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccount',
            name='id',
            field=models.TextField(default='d6a1c4e0684a4155bdd6b6fa12e4d05b', primary_key=True, serialize=False),
        ),
    ]
