# Generated by Django 3.2.6 on 2022-08-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_refaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccount',
            name='id',
            field=models.TextField(default='b4faf9c0d375443a987e21a9ca4dd3b3', primary_key=True, serialize=False),
        ),
    ]
