# Generated by Django 3.2.6 on 2022-10-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_refaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccount',
            name='id',
            field=models.TextField(default='f41f702cf2a943ccb198e125a4999ab8', primary_key=True, serialize=False),
        ),
    ]
